yay -S --noconfirm base-devel
yay -S --noconfirm brave-bin
yay -S --noconfirm btop
yay -S --noconfirm clang
yay -S --noconfirm curl
yay -S --noconfirm fastfetch
yay -S --noconfirm firefox
yay -S --noconfirm fzf
yay -S --noconfirm gcc
yay -S --noconfirm gdb
yay -S --noconfirm ghostty
yay -S --noconfirm git
yay -S --noconfirm grep
yay -S --noconfirm htop
yay -S --noconfirm llvm
yay -S --noconfirm pavucontrol
yay -S --noconfirm pipewire
yay -S --noconfirm playerctl
yay -S --noconfirm polkit
yay -S --noconfirm print-manager
yay -S --noconfirm pulseaudio
yay -S --noconfirm python
yay -S --noconfirm ripgrep
yay -S --noconfirm rustup
yay -S --noconfirm sed
yay -S --noconfirm snapper
yay -S --noconfirm stow
yay -S --noconfirm sudo
yay -S --noconfirm tmux
yay -S --noconfirm unzip
yay -S --noconfirm vim
yay -S --noconfirm wget
yay -S --noconfirm which
yay -S --noconfirm wofi
yay -S --noconfirm yay-bin
